CXX=g++

library:
	make -f galapaegos/Makefile
	make -f libgeom/Makefile
	make -f libgl/Makefile
	make -f libimage/Makefile
	make -f libphysicz/Makefile
	make -f libnet/Makefile
	make -f libscene/Makefile
	make -f libutil/Makefile
	make -f libvfs/Makefile
